### ISSUE TITLE
Boomer Desktop Application

### ISSUE THREAD

**Issue by TechMaverik** [HLRobotics/BOOMER#1]
### PyQt UI Design Featues BOOMER v2

- [x] Generic Robot Controls (Move Forward, Sit, Stand etc) Window
- [x] Real Time Clock Display Window
- [x] Reminders and Notifications Window
- [x] Connectivity (Bluetooth) Window
- [ ] Camera Integration and Image Processing Controls Window
- [ ] User Personalization  Window
- [x] Games Window
- [ ] Face Changer Window

**Comment by Abhi-Jitz** [comment]
For implementation of UI, Right?

**Comment by TechMaverik** [comment]
> For implementation of UI, Right?
Exactly. 
Take a new branch from main and start the adventure. :p

**Comment by Abhi-Jitz** [comment]
> > For implementation of UI, Right?
> Exactly. 
> Take a new branch from main and start the adventure. :p

With pleasure:)
